Repository toy-land/frontend, pull requests merged in 2021-02, with the labels that each got.

#1 평소에 사용하던 프로젝트 보일러플레이트 환경 적용
  .eslintignore
  .eslintrc.js
  .gitignore
  craco.config.js
  jsconfig.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/.gitkeep
  src/atoms/index.js
  src/components/Button/Button.js
  src/components/Button/index.js
  src/components/index.js
  src/constants/dummy.json
  src/index.css
  src/index.js
  src/logo.svg
  src/modules/.gitkeep
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/index.jsx
  src/pages/LandingPage/LandingPage.js
  src/pages/LandingPage/index.js
  src/pages/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/globalStyles.js
  src/styles/theme.js
  src/utils/index.js
  yarn.lock
Labels: chore, env

#5 Tag 아토믹 컴포넌트 제작 완료
  .eslintrc.js
  src/App.js
  src/atoms/Tag/Tag.js
  src/atoms/Tag/index.js
  src/atoms/index.js
  src/constants/colorType.js
  src/constants/dummy.json
Labels: feature, style

#7 Crud modules 구현 완료
  .eslintrc.js
  .vscode/.settings.json
  package.json
  src/index.js
  src/modules/.gitkeep
  src/modules/getToy/actions.js
  src/modules/getToy/index.js
  src/modules/getToy/reducer.js
  src/modules/getToy/thunk.js
  src/modules/index.js
  src/modules/removeToy/actions.js
  src/modules/removeToy/index.js
  src/modules/removeToy/reducer.js
  src/modules/removeToy/thunk.js
  src/modules/updateToy/actions.js
  src/modules/updateToy/index.js
  src/modules/updateToy/reducer.js
  src/modules/updateToy/thunk.js
  src/modules/writeToy/actions.js
  src/modules/writeToy/index.js
  src/modules/writeToy/reducer.js
  src/modules/writeToy/thunk.js
  src/utils/api.js
  src/utils/asyncUtils.js
  yarn.lock
Labels: enhancement, feature

#13 랜딩페이지 헤더 컴포넌트 추가
  package.json
  src/App.js
  src/atoms/Tag/Tag.js
  src/components/CreateButton/CreateButton.js
  src/components/CreateButton/index.js
  src/components/Header/Header.js
  src/components/Header/index.js
  src/components/index.js
  src/pages/CreateToyPage/CreateToyPage.js
  src/pages/LandingPage/LandingPage.js
  src/pages/index.js
  src/styles/globalStyles.js
  yarn.lock
Labels: feature, style

#16 랜딩페이지 카드박스 추가
  .eslintrc.js
  src/components/Button/Button.js
  src/components/Button/index.js
  src/components/CardBox/Card.js
  src/components/CardBox/CardBox.js
  src/components/CardBox/index.js
  src/components/MainView/MainView.js
  src/components/MainView/index.js
  src/components/index.js
  src/constants/emojiTheme.js
  src/modules/getToy/reducer.js
  src/modules/getToy/thunk.js
  src/modules/removeToy/reducer.js
  src/modules/removeToy/thunk.js
  src/modules/updateToy/reducer.js
  src/modules/updateToy/thunk.js
  src/modules/writeToy/reducer.js
  src/modules/writeToy/thunk.js
  src/pages/LandingPage/LandingPage.js
  src/styles/globalStyles.js
  src/utils/api.js
  src/utils/asyncUtils.js
  src/utils/getActive.js
Labels: feature

#18 feature branch 통합 이슈 해결
  src/App.js
  src/components/CardBox/CardBox.js
  src/components/MainView/MainView.js
  src/components/index.js
  src/constants/emojiTheme.js
  src/pages/CreateToyPage/CreateToyPage.js
  src/pages/CreateToyPage/index.js
  src/pages/DetailPage/index.js
  src/pages/LandingPage/LandingPage.js
  src/pages/index.js
  src/utils/index.js
Labels: feature

#19 front Dockerfile, CI/CD 추가
  .github/workflows/toyland_front_cd.yml
  .github/workflows/toyland_front_ci.yml
  Dockerfile
Labels: env, feature

#21 카드 생성, 삭제 아이콘, DnD 구현
  package.json
  src/components/CardBox/Card.js
  src/components/CardBox/CardBox.js
  src/components/CardBox/CardContent.js
  src/components/CreateButton/CreateButton.js
  src/components/CreateButton/index.js
  src/components/Header/Header.js
  src/components/SideIconBox/Pencile.js
  src/components/SideIconBox/SideIcon.js
  src/components/SideIconBox/SideIconBox.js
  src/components/SideIconBox/Trash.js
  src/components/SideIconBox/index.js
  src/components/index.js
  src/constants/itemType.js
  src/constants/toyMock.js
  src/index.js
  src/modules/dragToy/actions.js
  src/modules/dragToy/index.js
  src/modules/dragToy/reducer.js
  src/modules/getToy/reducer.js
  src/modules/index.js
  src/pages/LandingPage/LandingPage.js
  src/styles/testImg.png
  yarn.lock
Labels: feature

#23 프로젝트 등록 뷰 및 기능 구현
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/assets/.gitkeep
  src/assets/GitHub.png
  src/components/MarkdownEditor/MarkdownEditor.js
  src/modules/getGithub/actions.js
  src/modules/getGithub/index.js
  src/modules/getGithub/reducer.js
  src/modules/getGithub/thunk.js
  src/modules/getSkills/actions.js
  src/modules/getSkills/reducer.js
  src/modules/getSkills/thunk.js
  src/modules/index.js
  src/pages/CreateToyPage/CreateToyPage.js
  src/pages/InputRepoPage/InputRepoPage.js
  src/pages/InputRepoPage/index.js
  src/pages/index.js
  src/styles/globalStyles.js
  src/utils/api.js
  yarn.lock
Labels: feature

#24 카드 삭제, 랜딩 표지 구현
  src/assets/images/LandingWallpaper.png
  src/assets/images/trash.png
  src/atoms/DeleteModal/DeleteModal.js
  src/atoms/DeleteModal/index.js
  src/atoms/Overlay/Overlay.js
  src/atoms/Overlay/index.js
  src/atoms/index.js
  src/components/CardBox/Card.js
  src/components/CardBox/CardBox.js
  src/components/DeleteBox/DeleteBox.js
  src/components/DeleteBox/index.js
  src/components/Header/Header.js
  src/components/MainView/MainView.js
  src/components/SideIconBox/SideIcon.js
  src/components/SideIconBox/Trash.js
  src/components/index.js
  src/modules/dragToy/reducer.js
  src/modules/removeToy/reducer.js
  src/pages/DeletePage/index.js
  src/pages/LandingPage/LandingPage.js
  src/pages/index.js
  src/styles/testImg.png
  src/utils/api.js
  src/utils/asyncUtils.js
Labels: feature

#26 Feat/write modal
  src/components/CardBox/CardBox.js
  src/components/CardBox/CardContent.js
  src/components/DeleteBox/DeleteBox.js
  src/constants/activeText.js
  src/pages/CreateToyPage/CreateToyPage.js
  src/pages/InputRepoPage/InputRepoPage.js
  src/pages/index.js
  src/styles/globalStyles.js
Labels: feature

#29 디테일 페이지 제작
  src/App.js
  src/components/CardBox/Card.js
  src/components/CardBox/CardBox.js
  src/components/MarkdownEditor/MarkdownEditor.js
  src/pages/CreateToyPage/CreateToyPage.js
  src/pages/DetailPage/DetailPage.js
Labels: feature

#32 스타일링 수정, 랜딩 페이지 스크롤 request 버그 해결
  src/components/CardBox/CardBox.js
  src/components/CardBox/CardContent.js
  src/components/Header/Header.js
  src/components/MainView/MainView.js
  src/components/SideIconBox/SideIconBox.js
  src/constants/activeText.js
  src/modules/getToy/actions.js
  src/modules/getToy/reducer.js
Labels: feature

#41 BASE CLEANING
  .github/workflows/toyland_front_cd.yml
  .github/workflows/toyland_front_ci.yml
  src/utils/api.js
Labels: style

#43 1차적으로 QA반영 및 당장 보이는 이슈 처리한 부분 반영
  .github/workflows/toyland_front_cd.yml
  public/favicon.ico
  src/components/CardBox/CardBox.js
  src/components/CardBox/CardContent.js
  src/components/MarkdownEditor/MarkdownEditor.js
  src/pages/InputRepoPage/InputRepoPage.js
  src/utils/api.js
Labels: chore

#44 overflow: auto; 시 scroll이 안먹는 문제 해결 및 스크롤 hide
  src/components/CardBox/CardBox.js
Labels: chore
